// Code generated by "stringer -type Type -trimprefix Type"; DO NOT EDIT.

package kv

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeInvalid - -1]
	_ = x[TypeObject-0]
	_ = x[TypeString-1]
	_ = x[TypeInt32-2]
	_ = x[TypeFloat32-3]
	_ = x[TypePointer-4]
	_ = x[TypeWString-5]
	_ = x[TypeColor-6]
	_ = x[TypeUint64-7]
	_ = x[TypeEnd-8]
	_ = x[TypeInt64-10]
}

const (
	_Type_name_0 = "InvalidObjectStringInt32Float32PointerWStringColorUint64End"
	_Type_name_1 = "Int64"
)

var (
	_Type_index_0 = [...]uint8{0, 7, 13, 19, 24, 31, 38, 45, 50, 56, 59}
)

func (i Type) String() string {
	switch {
	case -1 <= i && i <= 8:
		i -= -1
		return _Type_name_0[_Type_index_0[i]:_Type_index_0[i+1]]
	case i == 10:
		return _Type_name_1
	default:
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
